version: '3.8'

networks:
    sy6-network:
        driver: bridge

services:
  # mian symfony container
  php-fpm:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
      args:
        UID: "${DOCKER_PHP_UID:-1000}"
        GID: "${DOCKER_PHP_GID:-1000}"
        APP_DIR: "${APP_DIR:-/app}"
        APP_ENV: "${APP_ENV:-dev}"
    user: "${DOCKER_PHP_UID:-1000}:${DOCKER_PHP_GID:-1000}"
    container_name: sy6-php
    depends_on:
      - database
    restart: on-failure
    ports:
      - 9000:9000
    networks:
      - sy6-network
    volumes:
      - ./app:${APP_DIR:-/app}:rw,cached
    extra_hosts:
      # Ensure that host.docker.internal is correctly defined
      - host.docker.internal:host-gateway
  #for dev mail cetcher
  mailcatcher:
        image: schickling/mailcatcher
        container_name: sy6-mailcatcher
        ports:
            - "1025:1025"
            - "1080:1080"
        networks:
            - sy6-network
  # database
  database:
        image: postgres:15.1-alpine3.17
        container_name: sy6-database
        restart: on-failure
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD:-secret321}
            POSTGRES_USER: ${DB_USER:-user}
            POSTGRES_DB: ${DB_NAME:-db}
        ports:
            - "5432:5432"
        networks:
            - sy6-network

  # nginx
  nginx:
      build:
          context: ./docker/nginx
          dockerfile: Dockerfile
      container_name: sy6-nginx
      restart: on-failure
      ports:
          - "80:80"
      networks:
          - sy6-network
      volumes:
          - ./app:${APP_DIR:-/app}
          - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      depends_on:
          - php-fpm
