twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        '%kernel.project_dir%/templates': main
        '%kernel.project_dir%/templates/micro-post': mp

when@test:
    twig:
        strict_variables: true
